DFVS.jar : Main.class Graph.class Edge.class EdgeType.class
	jar cmvf META-INF/MANIFEST.MF DFVS.jar Main.class Graph.class Edge.class EdgeType.class

Main.class : Main.java
	javac Main.java

Graph.class : Graph.java
	javac Graph.java

Edge.class : Edge.java
	javac Edge.java

EdgeType.class : EdgeType.java
	javac EdgeType.java